### ISSUE TITLE
JSONからFileモデルへのパースに失敗する場合がある

### ISSUE THREAD

**Issue by marihachi** [mika-f/Disboard#11]
MisskeyClient.Drive.FilesAsync()で発生

例外メッセージ:
```
Error converting value {null} to type 'System.Boolean'. Path '[26].isSensitive', line 1, position 15892.
```
isSensitiveにnullが入ってくる場合があるらしい

**Comment by mika-f** [comment]
対応したけど、これはこれで行けないような気がしなくもない...

**Comment by marihachi** [comment]
isSensitiveがないときのデフォルトの挙動は表示がオープンなので、falseにしてしまっても良さそう

**Comment by marihachi** [comment]
? を付けることで動作するようにはなった

**Comment by mika-f** [comment]
`null` なときの値についてはちょっと考えてみる

**Comment by marihachi** [comment]
参考になるかも
https://github.com/syuilo/misskey/blob/c4e8cabae90b59d5842db2f789eb0cd8ee1fcac4/src/server/api/endpoints/drive/files/create.ts#L34-L40

**Comment by marihachi** [comment]
あくまでもAPIからのレスポンスを純粋に返す
という感じならnullで返すべきという見方もありそう
