### ISSUE TITLE
response.EnsureSuccessStatusCode()が投げるHttpRequestExceptionがアプリ側でハンドリングしにくい

### ISSUE THREAD

**Issue by marihachi** [mika-f/Disboard#3]
https://github.com/OrionDevelop/Disboard/blob/feature/misskey/Source/Disboard/AppClient.cs#L368-L428
この辺りで使われている、`response.EnsureSuccessStatusCode()`ですが、
成功ステータスではなかった場合には`HttpRequestException`が投げられるみたいですが、
その例外からステータスコードが簡単に取り出せないため、エラーハンドリングがしにくいです。

ステータスコードが分かるような例外を投げるように変更できないでしょうか。

**Comment by marihachi** [comment]
EnsureSuccessStatusCodeは使わないほうが良いかも知れない。
エラーの内容なども分からないので

**Comment by marihachi** [comment]
例外投げるのってわりと重いので、通常のエラーでは投げないのが理想なんだけどね

**Comment by mika-f** [comment]
例外使わない処理も出来なくもないけど、成功したレスポンスに例外情報を持たせるのはどうなん...というのもあり、例外で対応していきたく

**Comment by marihachi** [comment]
例外は仕方ないね

**Comment by mika-f** [comment]
一旦閉じます

**Comment by marihachi** [comment]
大丈夫そう！ありがとう
