### ISSUE TITLE
Disboard.MisskeyのMisskeyClient.Domainを公開して欲しい

### ISSUE THREAD

**Issue by marihachi** [mika-f/Disboard#5]
MisskeyClientをシリアライズして保存しておくときに、Domainもその保存内容に含めたい。

**Comment by marihachi** [comment]
internalになっているのは、なにか理由があるのかな

**Comment by mika-f** [comment]
AppClient クラスをシリアライズする発想がなかった

**Comment by marihachi** [comment]
色々AppClient が状態を持っているので、シリアライズするならこいつかなと思った

**Comment by mika-f** [comment]
なるほどー。
でもまあ、ドメイン取得部分はすでに

```cs
public new string Domain => base.Domain;
```

みたいなのが出てしまっているので、 public にしてしまおう

**Comment by marihachi** [comment]
ドメインもAppClientの共通プロパティで良さそう

**Comment by mika-f** [comment]
> Collection of **fediverse** client libraries for .NET Standard 2.0

なのでそうしよう

**Comment by mika-f** [comment]
マージ済み
